FROM python:3.11-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app
ENV FLASK_APP=app.py
ENV FLASK_ENV=production
EXPOSE 8080
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "app:create_app()"]
